name = "ts-gql"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-01-11"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
